-------------------------------------------
--Building (UA)
-------------------------------------------
INSERT INTO Buildings
		(Type,					Description,					Civilopedia,									Strategy,								Help,								MutuallyExclusiveGroup,	Cost,	HurryCostModifier,	MinAreaSize,	LandmarksTourismPercent,	GreatWorksTourismModifier,	BuildingClass,			ArtDefineTag,				PrereqTech,					PortraitIndex,	WonderSplashAnchor,	IconAtlas)
VALUES	('BUILDING_JWW_LOTEL',	'TXT_KEY_BUILDING_JWW_LOTEL',	'TXT_KEY_CIV5_BUILDINGS_JWW_LOTEL_TEXT',		'TXT_KEY_BUILDING_JWW_LOTEL_STRATEGY',	'TXT_KEY_BUILDING_JWW_LOTEL_HELP',	-1,						300,	25,					-1,				50,							50,							'BUILDINGCLASS_HOTEL',	'ART_DEF_BUILDING_HOTEL',	'TECH_REFRIGERATION',		4,				'R,T',				'JWW_SEYCHELLES_COLOR_ATLAS');

INSERT INTO	Building_Flavors
		(BuildingType,			FlavorType,			Flavor)
VALUES	('BUILDING_JWW_LOTEL',	'FLAVOR_CULTURE',	50);

INSERT INTO BuildingClasses
		(Type, 										DefaultBuilding, 					Description)
VALUES	('BUILDINGCLASS_JWW_SEYCHELLES_UB', 		'BUILDING_JWW_SEYCHELLES_UB', 		'TXT_KEY_BUILDING_JWW_SEYCHELLES_UB');

INSERT INTO Buildings      
        (TYPE,                              BuildingClass,						LandmarksTourismPercent,	GreatWorksTourismModifier,	Cost,  FaithCost, GreatWorkCount,   NeverCapture,  Description)
VALUES  ('BUILDING_JWW_SEYCHELLES_UB',		'BUILDINGCLASS_JWW_SEYCHELLES_UB',	25,							25,							-1,    -1,        -1,               1,             'TXT_KEY_BUILDING_JWW_SEYCHELLES_UB');
-------------------------------------------
--Unit (SCG Cruiser)
-------------------------------------------
INSERT INTO Units
		(Type,						Description,					Civilopedia,							Strategy,									Help,									Combat,	Cost,	Moves,	BaseSightRange,	Class,					CombatClass,				Domain,			DefaultUnitAI,			MilitarySupport,	MilitaryProduction,	Pillage,	IgnoreBuildingDefense,	Mechanized,	PrereqTech,			AdvancedStartCost,	MinAreaSize,	AirInterceptRange,	NukeDamageLevel,	CombatLimit,	XPValueAttack,	XPValueDefense,	UnitArtInfo,					ShowInPedia,	MoveRate,	UnitFlagIconOffset,	PortraitIndex,	IconAtlas,					UnitFlagAtlas)
VALUES	('UNIT_JWW_SCG_CRUISER',	'TXT_KEY_UNIT_JWW_SCG_CRUISER',	'TXT_KEY_CIV5_JWW_SCG_CRUISER_TEXT',	'TXT_KEY_UNIT_JWW_SCG_CRUISER_STRATEGY',	'TXT_KEY_UNIT_HELP_JWW_SCG_CRUISER',	55,		375,	6,		2,				'UNITCLASS_DESTROYER',	'UNITCOMBAT_NAVALMELEE',	'DOMAIN_SEA',	'UNITAI_ATTACK_SEA',	1,					1,					1,			1,						1,			'TECH_COMBUSTION',	60,					10,				2,					-1,					100,			3,				3,				'ART_DEF_UNIT_JWW_SCG_CRUISER',	1,				'BOAT',		0,					2,				'JWW_SEYCHELLES_COLOR_ATLAS',	'JWW_SEYCHELLES_UNIT_ALPHA_ATLAS');

INSERT INTO Unit_AITypes
		(UnitType,						UnitAIType)
VALUES	('UNIT_JWW_SCG_CRUISER',	'UNITAI_ATTACK_SEA'),
		('UNIT_JWW_SCG_CRUISER',	'UNITAI_RESERVE_SEA'),
		('UNIT_JWW_SCG_CRUISER',	'UNITAI_ESCORT_SEA'),
		('UNIT_JWW_SCG_CRUISER',	'UNITAI_EXPLORE_SEA');

INSERT INTO Unit_FreePromotions
		(UnitType,					PromotionType)
VALUES	('UNIT_JWW_SCG_CRUISER',	'PROMOTION_SEE_INVISIBLE_SUBMARINE'),
		('UNIT_JWW_SCG_CRUISER',	'PROMOTION_INTERCEPTION_II'),
		('UNIT_JWW_SCG_CRUISER',	'PROMOTION_ANTI_SUBMARINE_II'),
		('UNIT_JWW_SCG_CRUISER',	'PROMOTION_WITHDRAW_BEFORE_MELEE');

INSERT INTO Unit_Flavors
		(UnitType,					FlavorType,				Flavor)
VALUES	('UNIT_JWW_SCG_CRUISER',	'FLAVOR_NAVAL',			18),
		('UNIT_JWW_SCG_CRUISER',	'FLAVOR_NAVAL_RECON',	4);

INSERT INTO UnitGameplay2DScripts
		(UnitType,					SelectionSound,				FirstSelectionSound)
VALUES	('UNIT_JWW_SCG_CRUISER',	'AS2D_SELECT_BATTLESHIP',	'AS2D_BIRTH_BATTLESHIP');
-------------------------------------------
--Leader (France-Albert René)
-------------------------------------------
INSERT INTO Leaders
		(Type,								Description,								Civilopedia,									CivilopediaTag,											ArtDefineTag,				VictoryCompetitiveness,	WonderCompetitiveness,	MinorCivCompetitiveness,	Boldness,	DiploBalance,	WarmongerHate,	WorkAgainstWillingness,	WorkWithWillingness,	DenounceWillingness,	DoFWillingness,	Loyalty,	Neediness,	Forgiveness,	Chattiness,	Meanness,	PortraitIndex,	IconAtlas)
VALUES	('LEADER_JWW_FRANCE-ALBERT_RENE',	'TXT_KEY_LEADER_JWW_FRANCE-ALBERT_RENE',	'TXT_KEY_LEADER_JWW_FRANCE-ALBERT_RENE_PEDIA',	'TXT_KEY_CIVILOPEDIA_LEADERS_JWW_FRANCE-ALBERT_RENE',	'AlbertReneScene.xml',		3,						3,						7,							6,			5,				7,				4,						7,						7,						7,				7,			9,			4,				5,			3,			0,				'JWW_SEYCHELLES_COLOR_ATLAS');

INSERT INTO Leader_MajorCivApproachBiases
		(LeaderType,						MajorCivApproachType,			Bias)
VALUES	('LEADER_JWW_FRANCE-ALBERT_RENE',	'MAJOR_CIV_APPROACH_WAR',		3),
		('LEADER_JWW_FRANCE-ALBERT_RENE',	'MAJOR_CIV_APPROACH_HOSTILE',	4),
		('LEADER_JWW_FRANCE-ALBERT_RENE',	'MAJOR_CIV_APPROACH_DECEPTIVE',	5),
		('LEADER_JWW_FRANCE-ALBERT_RENE',	'MAJOR_CIV_APPROACH_GUARDED',	6),
		('LEADER_JWW_FRANCE-ALBERT_RENE',	'MAJOR_CIV_APPROACH_AFRAID',	7),
		('LEADER_JWW_FRANCE-ALBERT_RENE',	'MAJOR_CIV_APPROACH_FRIENDLY',	8),
		('LEADER_JWW_FRANCE-ALBERT_RENE',	'MAJOR_CIV_APPROACH_NEUTRAL',	9);

INSERT INTO Leader_MinorCivApproachBiases
		(LeaderType,						MinorCivApproachType,				Bias)
VALUES	('LEADER_JWW_FRANCE-ALBERT_RENE',	'MINOR_CIV_APPROACH_IGNORE',		4),
		('LEADER_JWW_FRANCE-ALBERT_RENE',	'MINOR_CIV_APPROACH_FRIENDLY',		6),
		('LEADER_JWW_FRANCE-ALBERT_RENE',	'MINOR_CIV_APPROACH_PROTECTIVE',	5),
		('LEADER_JWW_FRANCE-ALBERT_RENE',	'MINOR_CIV_APPROACH_CONQUEST',		8),
		('LEADER_JWW_FRANCE-ALBERT_RENE',	'MINOR_CIV_APPROACH_BULLY',			9);

INSERT INTO	Leader_Flavors
		(LeaderType,					FlavorType,							Flavor)
VALUES	('LEADER_JWW_FRANCE-ALBERT_RENE',	'FLAVOR_OFFENSE',					8),
		('LEADER_JWW_FRANCE-ALBERT_RENE',	'FLAVOR_DEFENSE',					5),
		('LEADER_JWW_FRANCE-ALBERT_RENE',	'FLAVOR_CITY_DEFENSE',				4),
		('LEADER_JWW_FRANCE-ALBERT_RENE',	'FLAVOR_MILITARY_TRAINING',			5),
		('LEADER_JWW_FRANCE-ALBERT_RENE',	'FLAVOR_RECON',						3),
		('LEADER_JWW_FRANCE-ALBERT_RENE',	'FLAVOR_RANGED',					3),
		('LEADER_JWW_FRANCE-ALBERT_RENE',	'FLAVOR_MOBILE',					3),
		('LEADER_JWW_FRANCE-ALBERT_RENE',	'FLAVOR_NAVAL',						7),
		('LEADER_JWW_FRANCE-ALBERT_RENE',	'FLAVOR_NAVAL_RECON',				8),
		('LEADER_JWW_FRANCE-ALBERT_RENE',	'FLAVOR_NAVAL_GROWTH',				9),
		('LEADER_JWW_FRANCE-ALBERT_RENE',	'FLAVOR_NAVAL_TILE_IMPROVEMENT',	1),
		('LEADER_JWW_FRANCE-ALBERT_RENE',	'FLAVOR_AIR',						6),
		('LEADER_JWW_FRANCE-ALBERT_RENE',	'FLAVOR_EXPANSION',					8),
		('LEADER_JWW_FRANCE-ALBERT_RENE',	'FLAVOR_GROWTH',					4),
		('LEADER_JWW_FRANCE-ALBERT_RENE',	'FLAVOR_TILE_IMPROVEMENT',			5),
		('LEADER_JWW_FRANCE-ALBERT_RENE',	'FLAVOR_INFRASTRUCTURE',			8),
		('LEADER_JWW_FRANCE-ALBERT_RENE',	'FLAVOR_PRODUCTION',				4),
		('LEADER_JWW_FRANCE-ALBERT_RENE',	'FLAVOR_GOLD',						7),
		('LEADER_JWW_FRANCE-ALBERT_RENE',	'FLAVOR_SCIENCE',					4),
		('LEADER_JWW_FRANCE-ALBERT_RENE',	'FLAVOR_CULTURE',					8),
		('LEADER_JWW_FRANCE-ALBERT_RENE',	'FLAVOR_HAPPINESS',					8),
		('LEADER_JWW_FRANCE-ALBERT_RENE',	'FLAVOR_GREAT_PEOPLE',				6),
		('LEADER_JWW_FRANCE-ALBERT_RENE',	'FLAVOR_WONDER',					4),
		('LEADER_JWW_FRANCE-ALBERT_RENE',	'FLAVOR_RELIGION',					3),
		('LEADER_JWW_FRANCE-ALBERT_RENE',	'FLAVOR_DIPLOMACY',					6),
		('LEADER_JWW_FRANCE-ALBERT_RENE',	'FLAVOR_SPACESHIP',					4),
		('LEADER_JWW_FRANCE-ALBERT_RENE',	'FLAVOR_WATER_CONNECTION',			9),
		('LEADER_JWW_FRANCE-ALBERT_RENE',	'FLAVOR_NUKE',						2),
		('LEADER_JWW_FRANCE-ALBERT_RENE',	'FLAVOR_USE_NUKE',					5),
		('LEADER_JWW_FRANCE-ALBERT_RENE',	'FLAVOR_ESPIONAGE',					5),
		('LEADER_JWW_FRANCE-ALBERT_RENE',	'FLAVOR_ANTIAIR',					6),
		('LEADER_JWW_FRANCE-ALBERT_RENE',	'FLAVOR_AIR_CARRIER',				8),
		('LEADER_JWW_FRANCE-ALBERT_RENE',	'FLAVOR_ARCHAEOLOGY',				7),
		('LEADER_JWW_FRANCE-ALBERT_RENE',	'FLAVOR_I_LAND_TRADE_ROUTE',		2),
		('LEADER_JWW_FRANCE-ALBERT_RENE',	'FLAVOR_I_SEA_TRADE_ROUTE',			8),
		('LEADER_JWW_FRANCE-ALBERT_RENE',	'FLAVOR_I_TRADE_ORIGIN',			6),
		('LEADER_JWW_FRANCE-ALBERT_RENE',	'FLAVOR_I_TRADE_DESTINATION',		4),
		('LEADER_JWW_FRANCE-ALBERT_RENE',	'FLAVOR_AIRLIFT',					3);

INSERT INTO Leader_Traits
		(LeaderType,					TraitType)
VALUES	('LEADER_JWW_FRANCE-ALBERT_RENE',	'TRAIT_JWW_FINIS_CORONAT_OPUS');
-------------------------------------------
--Trait (Finis Coronat Opus)
-------------------------------------------
INSERT INTO Traits
		(Type,								Description,							ShortDescription)
VALUES	('TRAIT_JWW_FINIS_CORONAT_OPUS',	'TXT_KEY_TRAIT_JWW_FINIS_CORONAT_OPUS',	'TXT_KEY_TRAIT_JWW_FINIS_CORONAT_OPUS_SHORT');

INSERT INTO BuildingClasses
		(Type, 									DefaultBuilding, 					Description)
VALUES	('BUILDINGCLASS_JWW_SEYCHELLES_UA', 	'BUILDING_JWW_SEYCHELLES_UA', 		'TXT_KEY_BUILDING_JWW_SEYCHELLES_UA');

INSERT INTO Buildings      
        (TYPE,                              BuildingClass,						Cost,  FaithCost, GreatWorkCount,   NeverCapture,  Description)
VALUES  ('BUILDING_JWW_SEYCHELLES_UA',		'BUILDINGCLASS_JWW_SEYCHELLES_UA',	-1,    -1,        -1,               1,             'TXT_KEY_BUILDING_JWW_SEYCHELLES_UA');

INSERT INTO Building_UnitCombatFreeExperiences  
        (BuildingType,						 UnitCombatType,							Experience)
VALUES  ('BUILDING_JWW_SEYCHELLES_UA',		'UNITCOMBAT_MELEE',                         1),
        ('BUILDING_JWW_SEYCHELLES_UA',		'UNITCOMBAT_RECON',                         1),
        ('BUILDING_JWW_SEYCHELLES_UA',		'UNITCOMBAT_ARCHER',                        1),
        ('BUILDING_JWW_SEYCHELLES_UA',		'UNITCOMBAT_MOUNTED',                       1),
        ('BUILDING_JWW_SEYCHELLES_UA',		'UNITCOMBAT_SIEGE',                         1),
        ('BUILDING_JWW_SEYCHELLES_UA',		'UNITCOMBAT_GUN',							1),
        ('BUILDING_JWW_SEYCHELLES_UA',		'UNITCOMBAT_ARMOR',                         1),
        ('BUILDING_JWW_SEYCHELLES_UA',		'UNITCOMBAT_HELICOPTER',                    1),
        ('BUILDING_JWW_SEYCHELLES_UA',		'UNITCOMBAT_NAVALRANGED',                   1),
        ('BUILDING_JWW_SEYCHELLES_UA',		'UNITCOMBAT_FIGHTER',                       1),
        ('BUILDING_JWW_SEYCHELLES_UA',		'UNITCOMBAT_BOMBER',                        1),
        ('BUILDING_JWW_SEYCHELLES_UA',		'UNITCOMBAT_NAVALMELEE',                    1);
-------------------------------------------
--Diplomacy Responses
-------------------------------------------
INSERT INTO Diplomacy_Responses
		(LeaderType,						  ResponseType,									   Response,																		Bias)
VALUES	('LEADER_JWW_FRANCE-ALBERT_RENE',     'RESPONSE_ATTACKED_HOSTILE',                     'TXT_KEY_LEADER_JWW_FRANCE-ALBERT_RENE_ATTACKED_GENERIC%',						500),
		('LEADER_JWW_FRANCE-ALBERT_RENE',     'RESPONSE_DEFEATED',                             'TXT_KEY_LEADER_JWW_FRANCE-ALBERT_RENE_DEFEATED%',								500),
		('LEADER_JWW_FRANCE-ALBERT_RENE',     'RESPONSE_DOW_GENERIC',                          'TXT_KEY_LEADER_JWW_FRANCE-ALBERT_RENE_DOW_GENERIC%',							500),
		('LEADER_JWW_FRANCE-ALBERT_RENE',     'RESPONSE_EXPANSION_SERIOUS_WARNING',            'TXT_KEY_LEADER_JWW_FRANCE-ALBERT_RENE_EXPANSION_SERIOUS_WARNING%',				500),
		('LEADER_JWW_FRANCE-ALBERT_RENE',     'RESPONSE_FIRST_GREETING',                       'TXT_KEY_LEADER_JWW_FRANCE-ALBERT_RENE_FIRSTGREETING%',							500),
		('LEADER_JWW_FRANCE-ALBERT_RENE',     'RESPONSE_GREETING_AT_WAR_HOSTILE',			   'TXT_KEY_LEADER_JWW_FRANCE-ALBERT_RENE_GREETING_AT_WAR_HOSTILE%',				500),
		('LEADER_JWW_FRANCE-ALBERT_RENE',     'RESPONSE_GREETING_POLITE_HELLO',                'TXT_KEY_LEADER_JWW_FRANCE-ALBERT_RENE_GREETING_POLITE_HELLO%',					500),
		('LEADER_JWW_FRANCE-ALBERT_RENE',     'RESPONSE_GREETING_NEUTRAL_HELLO',               'TXT_KEY_LEADER_JWW_FRANCE-ALBERT_RENE_GREETING_NEUTRAL_HELLO%',					500),
		('LEADER_JWW_FRANCE-ALBERT_RENE',     'RESPONSE_GREETING_HOSTILE_HELLO',               'TXT_KEY_LEADER_JWW_FRANCE-ALBERT_RENE_GREETING_HOSTILE_HELLO%',					500),
		('LEADER_JWW_FRANCE-ALBERT_RENE',     'RESPONSE_HOSTILE_AGGRESSIVE_MILITARY_WARNING',  'TXT_KEY_LEADER_JWW_FRANCE-ALBERT_RENE_HOSTILE_AGGRESSIVE_MILITARY_WARNING%',	500),
		('LEADER_JWW_FRANCE-ALBERT_RENE',     'RESPONSE_INFLUENTIAL_ON_AI',                    'TXT_KEY_LEADER_JWW_FRANCE-ALBERT_RENE_INFLUENTIAL_ON_AI%',						500),
		('LEADER_JWW_FRANCE-ALBERT_RENE',     'RESPONSE_INFLUENTIAL_ON_HUMAN',                 'TXT_KEY_LEADER_JWW_FRANCE-ALBERT_RENE_INFLUENTIAL_ON_HUMAN%',					500),	
		('LEADER_JWW_FRANCE-ALBERT_RENE',     'RESPONSE_LETS_HEAR_IT',                         'TXT_KEY_LEADER_JWW_FRANCE-ALBERT_RENE_LETS_HEAR_IT%',							500),
		('LEADER_JWW_FRANCE-ALBERT_RENE',     'RESPONSE_LUXURY_TRADE',                         'TXT_KEY_LEADER_JWW_FRANCE-ALBERT_RENE_LUXURY_TRADE%',							500),
		('LEADER_JWW_FRANCE-ALBERT_RENE',     'RESPONSE_NO_PEACE',                             'TXT_KEY_LEADER_JWW_FRANCE-ALBERT_RENE_NO_PEACE%',								500),
		('LEADER_JWW_FRANCE-ALBERT_RENE',     'RESPONSE_OPEN_BORDERS_EXCHANGE',                'TXT_KEY_LEADER_JWW_FRANCE-ALBERT_RENE_OPEN_BORDERS_EXCHANGE%',					500),
		('LEADER_JWW_FRANCE-ALBERT_RENE',     'RESPONSE_PEACE_MADE_BY_HUMAN_GRACIOUS',         'TXT_KEY_LEADER_JWW_FRANCE-ALBERT_RENE_LOSEWAR%',								500),
		('LEADER_JWW_FRANCE-ALBERT_RENE',     'RESPONSE_REPEAT_NO',                            'TXT_KEY_LEADER_JWW_FRANCE-ALBERT_RENE_REPEAT_NO%',								500),
		('LEADER_JWW_FRANCE-ALBERT_RENE',     'RESPONSE_RESPONSE_REQUEST',                     'TXT_KEY_LEADER_JWW_FRANCE-ALBERT_RENE_RESPONSE_REQUEST%',						500),
		('LEADER_JWW_FRANCE-ALBERT_RENE',     'RESPONSE_RESPONSE_TO_BEING_DENOUNCED',		   'TXT_KEY_LEADER_JWW_FRANCE-ALBERT_RENE_RESPONSE_TO_BEING_DENOUNCED%',			500),
		('LEADER_JWW_FRANCE-ALBERT_RENE',     'RESPONSE_TOO_SOON_NO_PEACE',                    'TXT_KEY_LEADER_JWW_FRANCE-ALBERT_RENE_TOO_SOON_NO_PEACE_1%',					500),
		('LEADER_JWW_FRANCE-ALBERT_RENE',     'RESPONSE_WINNER_PEACE_OFFER',                   'TXT_KEY_LEADER_JWW_FRANCE-ALBERT_RENE_WINWAR%',									500),
		('LEADER_JWW_FRANCE-ALBERT_RENE',     'RESPONSE_WORK_AGAINST_SOMEONE',                 'TXT_KEY_LEADER_JWW_FRANCE-ALBERT_RENE_DENOUNCE%',								500),
		('LEADER_JWW_FRANCE-ALBERT_RENE',     'RESPONSE_WORK_WITH_US',                         'TXT_KEY_LEADER_JWW_FRANCE-ALBERT_RENE_DEC_FRIENDSHIP%',							500);
-------------------------------------------
--Civilization (Seychelles)
-------------------------------------------
INSERT INTO Civilizations
		(Type,							Description,						Civilopedia,						CivilopediaTag,					Playable,	AIPlayable,	ShortDescription,							Adjective,								DefaultPlayerColor,				ArtDefineTag,						ArtStyleType,						ArtStyleSuffix,		ArtStylePrefix,		PortraitIndex,	IconAtlas,						AlphaIconAtlas,					MapImage,				DawnOfManQuote,								DawnOfManImage,			SoundtrackTag)
VALUES	('CIVILIZATION_JWW_SEYCHELLES',	'TXT_KEY_CIV_JWW_SEYCHELLES_DESC',	'TXT_KEY_CIV_JWW_SEYCHELLES_PEDIA',	'TXT_KEY_CIV5_JWW_SEYCHELLES',	1,			1,			'TXT_KEY_CIV_JWW_SEYCHELLES_SHORT_DESC',	'TXT_KEY_CIV_JWW_SEYCHELLES_ADJECTIVE',	'PLAYERCOLOR_JWW_SEYCHELLES',	'ART_DEF_CIVILIZATION_POLYNESIA',	'ARTSTYLE_MIDDLE_EAST',				'_AFRI',			'AFRICAN',			1,				'JWW_SEYCHELLES_COLOR_ATLAS',	'JWW_SEYCHELLES_ALPHA_ATLAS',	'SeychellesMap.dds',	'TXT_KEY_CIV5_DAWN_JWW_SEYCHELLES_TEXT',	'AlbertRene_DOM.dds',	'France');

INSERT INTO Civilization_Leaders
		(CivilizationType,				LeaderheadType)
VALUES	('CIVILIZATION_JWW_SEYCHELLES',	'LEADER_JWW_FRANCE-ALBERT_RENE');

INSERT INTO Civilization_BuildingClassOverrides
		(CivilizationType,				BuildingClassType,		BuildingType)
VALUES	('CIVILIZATION_JWW_SEYCHELLES',	'BUILDINGCLASS_HOTEL',	'BUILDING_JWW_LOTEL');

INSERT INTO Civilization_UnitClassOverrides
		(CivilizationType,				UnitClassType,			UnitType)
VALUES	('CIVILIZATION_JWW_SEYCHELLES',	'UNITCLASS_DESTROYER',	'UNIT_JWW_SCG_CRUISER');

INSERT INTO Civilization_FreeBuildingClasses
		(CivilizationType,				BuildingClassType)
VALUES	('CIVILIZATION_JWW_SEYCHELLES',	'BUILDINGCLASS_PALACE');

INSERT INTO Civilization_FreeTechs
		(CivilizationType,				TechType)
VALUES	('CIVILIZATION_JWW_SEYCHELLES',	'TECH_AGRICULTURE');

INSERT INTO Civilization_FreeUnits
		(CivilizationType,				UnitClassType,			UnitAIType,			Count)
VALUES	('CIVILIZATION_JWW_SEYCHELLES',	'UNITCLASS_SETTLER',	'UNITAI_SETTLE',	1);

INSERT INTO Civilization_Religions
       (CivilizationType,				ReligionType)
VALUES ('CIVILIZATION_JWW_SEYCHELLES', 'RELIGION_CHRISTIANITY');

INSERT INTO Civilization_Start_Along_Ocean
		(CivilizationType,				StartAlongOcean)
VALUES	('CIVILIZATION_JWW_SEYCHELLES',	1);

INSERT INTO	Civilization_CityNames
		(CivilizationType,				CityName)
VALUES	('CIVILIZATION_JWW_SEYCHELLES',	'TXT_KEY_CITY_NAME_JWW_SEYCHELLES_0'),
		('CIVILIZATION_JWW_SEYCHELLES',	'TXT_KEY_CITY_NAME_JWW_SEYCHELLES_1'),
		('CIVILIZATION_JWW_SEYCHELLES',	'TXT_KEY_CITY_NAME_JWW_SEYCHELLES_2'),
		('CIVILIZATION_JWW_SEYCHELLES',	'TXT_KEY_CITY_NAME_JWW_SEYCHELLES_3'),
		('CIVILIZATION_JWW_SEYCHELLES',	'TXT_KEY_CITY_NAME_JWW_SEYCHELLES_4'),
		('CIVILIZATION_JWW_SEYCHELLES',	'TXT_KEY_CITY_NAME_JWW_SEYCHELLES_5'),
		('CIVILIZATION_JWW_SEYCHELLES',	'TXT_KEY_CITY_NAME_JWW_SEYCHELLES_6'),
		('CIVILIZATION_JWW_SEYCHELLES',	'TXT_KEY_CITY_NAME_JWW_SEYCHELLES_7'),
		('CIVILIZATION_JWW_SEYCHELLES',	'TXT_KEY_CITY_NAME_JWW_SEYCHELLES_8'),
		('CIVILIZATION_JWW_SEYCHELLES',	'TXT_KEY_CITY_NAME_JWW_SEYCHELLES_9'),
		('CIVILIZATION_JWW_SEYCHELLES',	'TXT_KEY_CITY_NAME_JWW_SEYCHELLES_10'),
		('CIVILIZATION_JWW_SEYCHELLES',	'TXT_KEY_CITY_NAME_JWW_SEYCHELLES_11'),
		('CIVILIZATION_JWW_SEYCHELLES',	'TXT_KEY_CITY_NAME_JWW_SEYCHELLES_12'),
		('CIVILIZATION_JWW_SEYCHELLES',	'TXT_KEY_CITY_NAME_JWW_SEYCHELLES_13'),
		('CIVILIZATION_JWW_SEYCHELLES',	'TXT_KEY_CITY_NAME_JWW_SEYCHELLES_14'),
		('CIVILIZATION_JWW_SEYCHELLES',	'TXT_KEY_CITY_NAME_JWW_SEYCHELLES_15'),
		('CIVILIZATION_JWW_SEYCHELLES',	'TXT_KEY_CITY_NAME_JWW_SEYCHELLES_16'),
		('CIVILIZATION_JWW_SEYCHELLES',	'TXT_KEY_CITY_NAME_JWW_SEYCHELLES_17'),
		('CIVILIZATION_JWW_SEYCHELLES',	'TXT_KEY_CITY_NAME_JWW_SEYCHELLES_18'),
		('CIVILIZATION_JWW_SEYCHELLES',	'TXT_KEY_CITY_NAME_JWW_SEYCHELLES_19'),
		('CIVILIZATION_JWW_SEYCHELLES',	'TXT_KEY_CITY_NAME_JWW_SEYCHELLES_20'),
		('CIVILIZATION_JWW_SEYCHELLES',	'TXT_KEY_CITY_NAME_JWW_SEYCHELLES_21'),
		('CIVILIZATION_JWW_SEYCHELLES',	'TXT_KEY_CITY_NAME_JWW_SEYCHELLES_22'),
		('CIVILIZATION_JWW_SEYCHELLES',	'TXT_KEY_CITY_NAME_JWW_SEYCHELLES_23'),
		('CIVILIZATION_JWW_SEYCHELLES',	'TXT_KEY_CITY_NAME_JWW_SEYCHELLES_24'),
		('CIVILIZATION_JWW_SEYCHELLES',	'TXT_KEY_CITY_NAME_JWW_SEYCHELLES_25'),
		('CIVILIZATION_JWW_SEYCHELLES',	'TXT_KEY_CITY_NAME_JWW_SEYCHELLES_26'),
		('CIVILIZATION_JWW_SEYCHELLES',	'TXT_KEY_CITY_NAME_JWW_SEYCHELLES_27'),
		('CIVILIZATION_JWW_SEYCHELLES',	'TXT_KEY_CITY_NAME_JWW_SEYCHELLES_28'),
		('CIVILIZATION_JWW_SEYCHELLES',	'TXT_KEY_CITY_NAME_JWW_SEYCHELLES_29'),
		('CIVILIZATION_JWW_SEYCHELLES',	'TXT_KEY_CITY_NAME_JWW_SEYCHELLES_30'),
		('CIVILIZATION_JWW_SEYCHELLES',	'TXT_KEY_CITY_NAME_JWW_SEYCHELLES_31'),
		('CIVILIZATION_JWW_SEYCHELLES',	'TXT_KEY_CITY_NAME_JWW_SEYCHELLES_32'),
		('CIVILIZATION_JWW_SEYCHELLES',	'TXT_KEY_CITY_NAME_JWW_SEYCHELLES_33'),
		('CIVILIZATION_JWW_SEYCHELLES',	'TXT_KEY_CITY_NAME_JWW_SEYCHELLES_34'),
		('CIVILIZATION_JWW_SEYCHELLES',	'TXT_KEY_CITY_NAME_JWW_SEYCHELLES_35'),
		('CIVILIZATION_JWW_SEYCHELLES',	'TXT_KEY_CITY_NAME_JWW_SEYCHELLES_36'),
		('CIVILIZATION_JWW_SEYCHELLES',	'TXT_KEY_CITY_NAME_JWW_SEYCHELLES_37'),
		('CIVILIZATION_JWW_SEYCHELLES',	'TXT_KEY_CITY_NAME_JWW_SEYCHELLES_38'),
		('CIVILIZATION_JWW_SEYCHELLES',	'TXT_KEY_CITY_NAME_JWW_SEYCHELLES_39'),
		('CIVILIZATION_JWW_SEYCHELLES',	'TXT_KEY_CITY_NAME_JWW_SEYCHELLES_40'),
		('CIVILIZATION_JWW_SEYCHELLES',	'TXT_KEY_CITY_NAME_JWW_SEYCHELLES_41'),
		('CIVILIZATION_JWW_SEYCHELLES',	'TXT_KEY_CITY_NAME_JWW_SEYCHELLES_42'),
		('CIVILIZATION_JWW_SEYCHELLES',	'TXT_KEY_CITY_NAME_JWW_SEYCHELLES_43'),
		('CIVILIZATION_JWW_SEYCHELLES',	'TXT_KEY_CITY_NAME_JWW_SEYCHELLES_44'),
		('CIVILIZATION_JWW_SEYCHELLES',	'TXT_KEY_CITY_NAME_JWW_SEYCHELLES_45'),
		('CIVILIZATION_JWW_SEYCHELLES',	'TXT_KEY_CITY_NAME_JWW_SEYCHELLES_46');
				
INSERT INTO Civilization_SpyNames
		(CivilizationType,					SpyName)
VALUES	('CIVILIZATION_JWW_SEYCHELLES',		'TXT_KEY_SPY_NAME_JWW_SEYCHELLES_0'),
		('CIVILIZATION_JWW_SEYCHELLES',		'TXT_KEY_SPY_NAME_JWW_SEYCHELLES_1'),
		('CIVILIZATION_JWW_SEYCHELLES',		'TXT_KEY_SPY_NAME_JWW_SEYCHELLES_2'),
		('CIVILIZATION_JWW_SEYCHELLES',		'TXT_KEY_SPY_NAME_JWW_SEYCHELLES_3'),
		('CIVILIZATION_JWW_SEYCHELLES',		'TXT_KEY_SPY_NAME_JWW_SEYCHELLES_4'),
		('CIVILIZATION_JWW_SEYCHELLES',		'TXT_KEY_SPY_NAME_JWW_SEYCHELLES_5'),
		('CIVILIZATION_JWW_SEYCHELLES',		'TXT_KEY_SPY_NAME_JWW_SEYCHELLES_6'),
		('CIVILIZATION_JWW_SEYCHELLES',		'TXT_KEY_SPY_NAME_JWW_SEYCHELLES_7'),
		('CIVILIZATION_JWW_SEYCHELLES',		'TXT_KEY_SPY_NAME_JWW_SEYCHELLES_8'),
		('CIVILIZATION_JWW_SEYCHELLES',		'TXT_KEY_SPY_NAME_JWW_SEYCHELLES_9');
--================================================================
--================================================================