INSERT INTO Diplomacy_Responses
		(LeaderType, 				ResponseType, 								Response, 														Bias)
VALUES 	('LEADER_PB_LUO_FANGBO', 	'RESPONSE_ATTACKED_HOSTILE', 				'TXT_KEY_LEADER_PB_LUO_FANGBO_ATTACKED_HOSTILE%', 				500),
		('LEADER_PB_LUO_FANGBO', 	'RESPONSE_DEFEATED', 						'TXT_KEY_LEADER_PB_LUO_FANGBO_DEFEATED%', 						500),
		('LEADER_PB_LUO_FANGBO', 	'RESPONSE_DOW_GENERIC', 					'TXT_KEY_LEADER_PB_LUO_FANGBO_DOW_GENERIC%', 					500),
		('LEADER_PB_LUO_FANGBO', 	'RESPONSE_FIRST_GREETING', 					'TXT_KEY_LEADER_PB_LUO_FANGBO_FIRSTGREETING%', 					500),
		('LEADER_PB_LUO_FANGBO', 	'RESPONSE_RESPONSE_TO_BEING_DENOUNCED', 	'TXT_KEY_LEADER_PB_LUO_FANGBO_RESPONSE_TO_BEING_DENOUNCED%', 	500),
		('LEADER_PB_LUO_FANGBO', 	'RESPONSE_WORK_AGAINST_SOMEONE', 			'TXT_KEY_LEADER_PB_LUO_FANGBO_DENOUNCE%', 						500),
		('LEADER_PB_LUO_FANGBO', 	'RESPONSE_WORK_WITH_US', 					'TXT_KEY_LEADER_PB_LUO_FANGBO_DEC_FRIENDSHIP%', 				500),
		('LEADER_PB_LUO_FANGBO', 	'RESPONSE_MINOR_CIV_COMPETITION', 			'TXT_KEY_LEADER_PB_LUO_FANGBO_MINOR_CIV_COMPETITION%', 			500),
		('LEADER_PB_LUO_FANGBO', 	'RESPONSE_TRADE_NEEDMORE_NEUTRAL', 			'TXT_KEY_LEADER_LF_LUO_FANGBO_TRADE_NEEDMORE_NEUTRAL%', 		500);