--==========================================================================================================================
-- ART
--==========================================================================================================================
INSERT INTO
	IconTextureAtlases (Atlas, IconSize, Filename, IconsPerRow, IconsPerColumn)
VALUES
	('LUNG_RELIGIONS_ATLAS', 256, 'LungRelAtlas256.dds', 4, 4),
	('LUNG_RELIGIONS_ATLAS', 214, 'LungRelAtlas214.dds', 4, 4),
	('LUNG_RELIGIONS_ATLAS', 128, 'LungRelAtlas128.dds', 4, 4),
	('LUNG_RELIGIONS_ATLAS', 80, 'LungRelAtlas80.dds', 4, 4),
	('LUNG_RELIGIONS_ATLAS', 64, 'LungRelAtlas64.dds', 4, 4),
	('LUNG_RELIGIONS_ATLAS', 48, 'LungRelAtlas48.dds', 4, 4),
	('LUNG_RELIGIONS_ATLAS', 32, 'LungRelAtlas32.dds', 4, 4),
	('LUNG_RELIGIONS_ATLAS', 24, 'LungRelAtlas24.dds', 4, 4),
	('LUNG_RELIGIONS_ATLAS', 16, 'LungRelAtlas16.dds', 4, 4);

INSERT INTO
	IconFontTextures (IconFontTexture, IconFontTextureFile)
VALUES
	('ICON_FONT_TEXTURE_LUNG_RELIGIONS', 'LungRelFont');

INSERT INTO
	IconFontMapping (IconName, IconFontTexture, IconMapping)
VALUES
	('ICON_RELIGION_ZUNISM', 'ICON_FONT_TEXTURE_LUNG_RELIGIONS', 0),
	('ICON_RELIGION_YZNGI', 'ICON_FONT_TEXTURE_LUNG_RELIGIONS', 1),
	('ICON_RELIGION_ULGANISM', 'ICON_FONT_TEXTURE_LUNG_RELIGIONS', 2),
	('ICON_RELIGION_LUNGSATSANAPHI', 'ICON_FONT_TEXTURE_LUNG_RELIGIONS', 3),
	('ICON_RELIGION_ATTARISM', 'ICON_FONT_TEXTURE_LUNG_RELIGIONS', 4),
	('ICON_RELIGION_MUNKHTENGER', 'ICON_FONT_TEXTURE_LUNG_RELIGIONS', 5),
	('ICON_RELIGION_ILLUISM', 'ICON_FONT_TEXTURE_LUNG_RELIGIONS', 14),
	('ICON_RELIGION_PHATGIAO', 'ICON_FONT_TEXTURE_LUNG_RELIGIONS', 15),
	('ICON_RELIGION_ALMAQAHISM', 'ICON_FONT_TEXTURE_LUNG_RELIGIONS', 6),
	('ICON_RELIGION_AKSERIBUGA', 'ICON_FONT_TEXTURE_LUNG_RELIGIONS', 7),
	('ICON_RELIGION_HUBALISM', 'ICON_FONT_TEXTURE_LUNG_RELIGIONS', 8),
	('ICON_RELIGION_KUPTYNG', 'ICON_FONT_TEXTURE_LUNG_RELIGIONS', 9),
	('ICON_RELIGION_ABKAI', 'ICON_FONT_TEXTURE_LUNG_RELIGIONS', 10),
	('ICON_RELIGION_BALAMON', 'ICON_FONT_TEXTURE_LUNG_RELIGIONS', 12),
	('ICON_RELIGION_KRISTNI', 'ICON_FONT_TEXTURE_LUNG_RELIGIONS', 13);

--==========================================================================================================================
-- RELIGIONS
--==========================================================================================================================
INSERT INTO
	Religions (Type, Description, Civilopedia, IconAtlas, PortraitIndex, IconString)
VALUES
	('RELIGION_ZUNISM', 'TXT_KEY_RELIGION_ZUNISM', 'TXT_KEY_RELIGION_ZUNISM_PEDIA', 'LUNG_RELIGIONS_ATLAS', 0, '[ICON_RELIGION_ZUNISM]'),
	('RELIGION_YZNGI', 'TXT_KEY_RELIGION_YZNGI', 'TXT_KEY_RELIGION_YZNGI_PEDIA', 'LUNG_RELIGIONS_ATLAS', 1, '[ICON_RELIGION_YZNGI]'),
	('RELIGION_ULGANISM', 'TXT_KEY_RELIGION_ULGANISM', 'TXT_KEY_RELIGION_ULGANISM_PEDIA', 'LUNG_RELIGIONS_ATLAS', 2, '[ICON_RELIGION_ULGANISM]'),
	('RELIGION_LUNGSATSANAPHI', 'TXT_KEY_RELIGION_LUNGSATSANAPHI', 'TXT_KEY_RELIGION_LUNGSATSANAPHI_PEDIA', 'LUNG_RELIGIONS_ATLAS', 3, '[ICON_RELIGION_LUNGSATSANAPHI]'),
	('RELIGION_ATTARISM', 'TXT_KEY_RELIGION_ATTARISM', 'TXT_KEY_RELIGION_ATTARISM_PEDIA', 'LUNG_RELIGIONS_ATLAS', 4, '[ICON_RELIGION_ATTARISM]'),
	('RELIGION_MUNKHTENGER', 'TXT_KEY_RELIGION_MUNKHTENGER', 'TXT_KEY_RELIGION_MUNKHTENGER_PEDIA', 'LUNG_RELIGIONS_ATLAS', 5, '[ICON_RELIGION_MUNKHTENGER]'),
	('RELIGION_ILLUISM', 'TXT_KEY_RELIGION_ILLUISM', 'TXT_KEY_RELIGION_ILLUISM_PEDIA', 'LUNG_RELIGIONS_ATLAS', 14, '[ICON_RELIGION_ILLUISM]'),
	('RELIGION_PHATGIAO', 'TXT_KEY_RELIGION_PHATGIAO', 'TXT_KEY_RELIGION_PHATGIAO_PEDIA', 'LUNG_RELIGIONS_ATLAS', 15, '[ICON_RELIGION_PHATGIAO]'),
	('RELIGION_ALMAQAHISM', 'TXT_KEY_RELIGION_ALMAQAHISM', 'TXT_KEY_RELIGION_ALMAQAHISM_PEDIA', 'LUNG_RELIGIONS_ATLAS', 6, '[ICON_RELIGION_ALMAQAHISM]'),
	('RELIGION_AKSERIBUGA', 'TXT_KEY_RELIGION_AKSERIBUGA', 'TXT_KEY_RELIGION_AKSERIBUGA_PEDIA', 'LUNG_RELIGIONS_ATLAS', 7, '[ICON_RELIGION_AKSERIBUGA]'),
	('RELIGION_HUBALISM', 'TXT_KEY_RELIGION_HUBALISM', 'TXT_KEY_RELIGION_HUBALISM_PEDIA', 'LUNG_RELIGIONS_ATLAS', 8, '[ICON_RELIGION_KUPTYNG]'),
	('RELIGION_KUPTYNG', 'TXT_KEY_RELIGION_KUPTYNG', 'TXT_KEY_RELIGION_KUPTYNG_PEDIA', 'LUNG_RELIGIONS_ATLAS', 9, '[ICON_RELIGION_ATTARISM]'),
	('RELIGION_ABKAI', 'TXT_KEY_RELIGION_ABKAI', 'TXT_KEY_RELIGION_ABKAI_PEDIA', 'LUNG_RELIGIONS_ATLAS', 10, '[ICON_RELIGION_ABKAI]'),
	('RELIGION_BALAMON', 'TXT_KEY_RELIGION_BALAMON', 'TXT_KEY_RELIGION_BALAMON_PEDIA', 'LUNG_RELIGIONS_ATLAS', 12, '[ICON_RELIGION_BALAMON]'),
	('RELIGION_KRISTNI', 'TXT_KEY_RELIGION_KRISTNI', 'TXT_KEY_RELIGION_KRISTNI_PEDIA', 'LUNG_RELIGIONS_ATLAS', 13, '[ICON_RELIGION_KRISTNI]');

--==========================================================================================================================
-- PREFERENCES
--==========================================================================================================================
-- Saba-Dmt
--DELETE FROM Civilization_Religions WHERE CivilizationType = 'CIVILIZATION_EW_SHEBA';
--INSERT INTO Civilization_Religions
--		        (CivilizationType,	ReligionType)
--SELECT		Type,			('RELIGION_ZUNISM')
-- Civilizations WHERE Type = 'CIVILIZATION_EW_SHEBA';
--UPDATE Civilization_Religions SET ReligionType =
--	( CASE WHEN EXISTS(SELECT Type FROM Religions WHERE Type = 'RELIGION_ALMAQAHISM' )
--		THEN 'RELIGION_ALMAQAHISM'
--		ELSE 'RELIGION_ORIENTAL_ORTHODOXY' END
--	) WHERE CivilizationType = 'CIVILIZATION_EW_SHEBA';
--CREATE TRIGGER CivilizationShebaLungRel
--AFTER INSERT ON Civilization_Religions WHEN 'CIVILIZATION_EW_SHEBA' = NEW.CivilizationType
--BEGIN
--	UPDATE Civilization_Religions SET ReligionType =
--		( CASE WHEN EXISTS(SELECT Type FROM Religions WHERE Type = 'RELIGION_ZUNISM' )
--			THEN 'RELIGION_ALMAQAHISM'
--			ELSE 'RELIGION_ORIENTAL_ORTHODOXY' END
--		) WHERE CivilizationType = 'CIVILIZATION_EW_SHEBA';
--END;
--==========================================================================================================================
--==========================================================================================================================