--Minimum Tile distance between Cities
UPDATE Defines
SET
	Value = 3
WHERE
	Name = 'MIN_CITY_RANGE';

-- Maximum working range for Cities
UPDATE Defines
SET
	Value = 4
WHERE
	Name IN (
		'MAXIMUM_WORK_PLOT_DISTANCE',
		'MAXIMUM_BUY_PLOT_DISTANCE'
	);

-- Citis take less damage on Capture
UPDATE Defines
SET
	Value = 70
WHERE
	Name IN (
		'CITY_CAPTURE_POPULATION_PERCENT',
		'CITY_CAPTURE_DAMAGE_PERCENT'
	);

UPDATE Defines
SET
	Value = 50
WHERE
	Name = 'CAPTURE_GOLD_PER_POPULATION';

UPDATE Buildings
SET
	ConquestProb = 70
WHERE
	Type IN (
		'BUILDING_FLOATING_GARDENS',
		'BUILDING_LONGHOUSE',
		'BUILDING_PAPER_MAKER',
		'BUILDING_WAT',
		'BUILDING_SEAPORT',
		'BUILDING_WATERMILL',
		'BUILDING_WINDMILL',
		'BUILDING_HYDRO_PLANT',
		'BUILDING_SOLAR_PLANT',
		'BUILDING_OBSERVATORY',
		'BUILDING_GARDEN',
		'BUILDING_LIGHTHOUSE',
		'BUILDING_HARBOR',
		'BUILDING_MILITARY_BASE',
		'BUILDING_GRANARY',
		'BUILDING_HOSPITAL',
		'BUILDING_MEDICAL_LAB',
		'BUILDING_WORKSHOP',
		'BUILDING_FACTORY',
		'BUILDING_NUCLEAR_PLANT',
		'BUILDING_LIBRARY',
		'BUILDING_UNIVERSITY',
		'BUILDING_PUBLIC_SCHOOL',
		'BUILDING_LABORATORY',
		'BUILDING_AQUEDUCT',
		'BUILDING_STONE_WORKS',
		'BUILDING_BAZAAR',
		'BUILDING_SATRAPS_COURT',
		'BUILDING_MARKET',
		'BUILDING_BANK',
		'BUILDING_STOCK_EXCHANGE',
		'BUILDING_MUD_PYRAMID_MOSQUE',
		'BUILDING_BURIAL_TOMB',
		'BUILDING_CIRCUS',
		'BUILDING_FORGE',
		'BUILDING_MONASTERY',
		'BUILDING_COLOSSEUM',
		'BUILDING_THEATRE',
		'BUILDING_STADIUM',
		'BUILDING_TEMPLE'
	);

-- Production from Jungle
UPDATE BuildFeatures
SET
	Production = (
		SELECT
			Production * 3 / 4
		FROM
			BuildFeatures
		WHERE
			FeatureType = 'FEATURE_FOREST'
			AND RemoveOnly = 1
	)
WHERE
	FeatureType = 'FEATURE_JUNGLE'
	AND (
		BuildType = 'BUILD_REMOVE_JUNGLE'
		OR BuildType IN (
			SELECT
				BuildType
			FROM
				BuildFeatures
			WHERE
				FeatureType = 'FEATURE_FOREST'
				AND Production > 0
		)
	);

--Nuke City destruction adjustment
UPDATE Defines
SET
	Value = 3
WHERE
	Name = 'NUKE_LEVEL2_ELIM_POPULATION_THRESHOLD';
