-- Ensure the table exists and correctly formatted
CREATE TABLE IF NOT EXISTS CustomModOptions (
	Name TEXT,
	Value INTEGER,
	Class INTEGER,
	DbUpdates INTEGER
);

-- Insert or replace into CustomModOptions
INSERT
OR REPLACE INTO CustomModOptions (Name, Value)
VALUES
	('API_EXTENSIONS', 1);

-- Update existing ReligionType values for specific Civilizations
-- UPDATE Civilization_Religions
-- SET
-- 	ReligionType = CASE CivilizationType
-- 		WHEN 'CIVILIZATION_JWW_BORA_BORA' THEN 'RELIGION_PUTA_TUPUNA'
-- 		WHEN 'CIVILIZATION_GT_FINNS' THEN 'RELIGION_TAIVAANAULA'
-- 		WHEN 'CIVILIZATION_MC_GOGURYEO' THEN 'RELIGION_MUISM'
-- 		WHEN 'CIVILIZATION_HARAPPA_MOD' THEN 'RELIGION_AKATTU'
-- 		WHEN 'CIVILIZATION_EW_KHOSHUT' THEN 'RELIGION_BON'
-- 		WHEN 'CIVILIZATION_JFD_MEXICO_MAXIMILIAN_I' THEN 'RELIGION_IN_KALTONAL'
-- 		WHEN 'CIVILIZATION_EW_SHEBA' THEN 'RELIGION_ALMAQAHISM'
-- 		WHEN 'CIVILIZATION_ER_SINGAPORE' THEN 'RELIGION_SHAFII'
-- 		WHEN 'CIVILIZATION_TCM_VISIGOTH' THEN 'RELIGION_HAITHN'
-- 		WHEN 'CIVILIZATION_DMS_FAROE_ISLANDS' THEN 'RELIGION_KRISTNI'
-- 		WHEN 'CIVILIZATION_US_QARMATIANS' THEN 'RELIGION_HUBALISM'
-- 		WHEN 'CIVILIZATION_SENSHI_SELKUPS' THEN 'RELIGION_KUPTYNG'
-- 		WHEN 'CIVILIZATION_LUNG_DAI_VIET' THEN 'RELIGION_PHATGIAO'
-- 		WHEN 'CIVILIZATION_EW_NIVKH' THEN 'RELIGION_YZNGI'
-- 		WHEN 'CIVILIZATION_RHO_UME_SAMI' THEN 'RELIGION_NOAIDEVUOHTA'
-- 		WHEN 'CIVILIZATION_UC_TAINO' THEN 'RELIGION_ZEMIISM'
-- 		ELSE ReligionType
-- 	END
-- WHERE
-- 	CivilizationType IN (
-- 		'CIVILIZATION_JWW_BORA_BORA',
-- 		'CIVILIZATION_GT_FINNS',
-- 		'CIVILIZATION_MC_GOGURYEO',
-- 		'CIVILIZATION_HARAPPA_MOD',
-- 		'CIVILIZATION_EW_KHOSHUT',
-- 		'CIVILIZATION_JFD_MEXICO_MAXIMILIAN_I',
-- 		'CIVILIZATION_EW_SHEBA',
-- 		'CIVILIZATION_ER_SINGAPORE',
-- 		'CIVILIZATION_TCM_VISIGOTH',
-- 		'CIVILIZATION_DMS_FAROE_ISLANDS',
-- 		'CIVILIZATION_US_QARMATIANS',
-- 		'CIVILIZATION_SENSHI_SELKUPS',
-- 		'CIVILIZATION_LUNG_DAI_VIET',
-- 		'CIVILIZATION_EW_NIVKH',
-- 		'CIVILIZATION_RHO_UME_SAMI',
-- 		'CIVILIZATION_UC_TAINO'
-- 	);
-- Insert new Civilization-Religion backups
-- INSERT INTO
-- 	Civilization_Religions (CivilizationType, ReligionType)
-- VALUES
-- 	('CIVILIZATION_DMS_FAROE_ISLANDS', 'RELIGION_FORN_SIDR'),
-- 	('CIVILIZATION_JFD_BAVARIA_LUDWIG_II', 'RELIGION_CHRISTIANITY'),
-- 	('CIVILIZATION_JFD_BAVARIA_LUDWIG_II', 'RELIGION_IRMINISM'),
-- 	('CIVILIZATION_EW_FREETERRITORY', 'RELIGION_CHRISTIAN_CHURCH_OF_THE_EAST'),
-- 	('CIVILIZATION_GT_PONTUS', 'RELIGION_MITHRAISM'),
-- 	('CIVILIZATION_UC_ALAOUITE', 'RELIGION_FAT_ROOG'),
-- 	('CIVILIZATION_UC_ALAOUITE', 'RELIGION_ILLUISM'),
-- 	('CIVILIZATION_DMS_MC_KANEM_BORNU', 'RELIGION_ISLAM'),
-- 	('CIVILIZATION_DMS_MC_KANEM_BORNU', 'RELIGION_IMANA'),
-- 	('CIVILIZATION_DMS_MC_KANEM_BORNU', 'RELIGION_MUTAZILA'),
-- 	('CIVILIZATION_ZRQ_MAMLUK_SHAJAR', 'RELIGION_ISLAM_SHIA'),
-- 	('CIVILIZATION_ZRQ_MAMLUK_SHAJAR', 'RELIGION_PESEDJET'),
-- 	('CIVILIZATION_EW_SHEBA', 'RELIGION_AL_ASNAM'),
-- 	('CIVILIZATION_NC_NDONGO', 'RELIGION_NZAMBIISM'),
-- 	('CIVILIZATION_ER_MOGADISHU', 'RELIGION_ISLAM'),
-- 	('CIVILIZATION_ER_MOGADISHU', 'RELIGION_WAAQEFFANNAA'),
-- 	('CIVILIZATION_ER_KALMYKIA', 'RELIGION_VAJRAYANA'),
-- 	('CIVILIZATION_ER_KALMYKIA', 'RELIGION_MUNKHTENGER'),
-- 	('CIVILIZATION_ER_KALMYKIA', 'RELIGION_MAHAYANA'),
-- 	('CIVILIZATION_MC_GOGURYEO', 'RELIGION_MAHAYANA'),
-- 	('CIVILIZATION_LUNG_DAI_VIET', 'RELIGION_MAHAYANA'),
-- 	('CIVILIZATION_NC_MAGUINDANAO', 'RELIGION_ANITO'),
-- 	('CIVILIZATION_SAS_PUEBLO', 'RELIGION_KACHINA'),
-- 	('CIVILIZATION_GPUZ_SHAWNEE', 'RELIGION_MIDEWIWIN'),
-- 	('CIVILIZATION_MC_NTF_SENECA', 'RELIGION_GAIHWIIO'),
-- 	('CIVILIZATION_TIWANAKU', 'RELIGION_PACHISM'),
-- 	('CIVILIZATION_TIWANAKU', 'RELIGION_INTIISM'),
-- 	('CIVILIZATION_JWW_RIOGRANDENSE_REPUBLIC', 'RELIGION_CHRISTIANITY'),
-- 	('CIVILIZATION_JWW_RIOGRANDENSE_REPUBLIC', 'RELIGION_PAJELANCA'),
-- 	('CIVILIZATION_EW_NIVKH', 'RELIGION_ANGAKKUQISM'),
-- 	('CIVILIZATION_THP_YELLOWKNIFE', 'RELIGION_SGAANAANG'),
-- 	('CIVILIZATION_SAS_PALAWA', 'RELIGION_MURAYMIN'),
-- 	('CIVILIZATION_JWW_SIERRA_LEONE_PETERS', 'RELIGION_PROTESTANT_METHODISM'),
-- 	('CIVILIZATION_THP_NOONGAR', 'RELIGION_TJUKURPA'),
-- 	('CIVILIZATION_SHANG_MOD', 'RELIGION_SOLAR_BIRD_CULT'),
-- 	('CIVILIZATION_EW_TUNGNING', 'RELIGION_KAWASKAWAS'),
-- 	('CIVILIZATION_AGLA_KAZAN', 'RELIGION_AJDAHA_YILAN');
