-- Insert SQL Rules Here 
--==========================================================================================================================
-- Diplomacy_Responses
--==========================================================================================================================
INSERT INTO Diplomacy_Responses
(LeaderType, 				ResponseType, 											Response, 																	Bias)
VALUES		('LEADER_CLPONTIAC', 	'RESPONSE_MINOR_CIV_COMPETITION', 						'TXT_KEY_LEADER_CLPONTIAC_MINOR_CIV_COMPETITION%', 						2),
('LEADER_CLPONTIAC', 	'RESPONSE_FIRST_GREETING', 								'TXT_KEY_LEADER_CLPONTIAC_FIRSTGREETING%', 								2),
('LEADER_CLPONTIAC', 	'RESPONSE_DEFEATED', 									'TXT_KEY_LEADER_CLPONTIAC_DEFEATED%', 									2),
('LEADER_CLPONTIAC', 	'RESPONSE_GREETING_REPEAT_TOO_MUCH', 					'TXT_KEY_LEADER_CLPONTIAC_REPEAT_TOO_MUCH%', 							2),
('LEADER_CLPONTIAC', 	'RESPONSE_REPEAT_TRADE_TOO_MUCH', 						'TXT_KEY_LEADER_CLPONTIAC_REPEAT_TRADE_TOO_MUCH%', 						2),
('LEADER_CLPONTIAC', 	'RESPONSE_GREETING_HOSTILE_REPEAT', 					'TXT_KEY_LEADER_CLPONTIAC_REPEAT_TOO_MUCH%', 							2),
('LEADER_CLPONTIAC', 	'RESPONSE_GREETING_HOSTILE_HELLO', 						'TXT_KEY_LEADER_CLPONTIAC_GREETING_HOSTILE_HELLO%', 					2),
('LEADER_CLPONTIAC', 	'RESPONSE_GREETING_POLITE_HELLO', 						'TXT_KEY_LEADER_CLPONTIAC_GREETING_POLITE_HELLO%', 						2),
('LEADER_CLPONTIAC', 	'RESPONSE_GREETING_HOSTILE_HUMAN_AT_WAR', 				'TXT_KEY_LEADER_CLPONTIAC_GREETING_HOSTILE_HUMAN_AT_WAR%', 				2),
('LEADER_CLPONTIAC', 	'RESPONSE_GREETING_HUMAN_AT_WAR', 						'TXT_KEY_LEADER_CLPONTIAC_GREETING_HUMAN_AT_WAR%', 						2),
('LEADER_CLPONTIAC', 	'RESPONSE_HOSTILE_AGGRESSIVE_MILITARY_WARNING', 		'TXT_KEY_LEADER_CLPONTIAC_HOSTILE_AGGRESSIVE_MILITARY_WARNING%', 		2),
('LEADER_CLPONTIAC', 	'RESPONSE_GREETING_AGGRESSIVE_MILITARY', 				'TXT_KEY_LEADER_CLPONTIAC_AGGRESSIVE_MILITARY_WARNING%', 				2),
('LEADER_CLPONTIAC', 	'RESPONSE_GREETING_HOSTILE_AGGRESSIVE_PLOT_BUYING', 	'TXT_KEY_LEADER_CLPONTIAC_GREETING_HOSTILE_AGGRESSIVE_PLOT_BUYING%', 	2),
('LEADER_CLPONTIAC', 	'RESPONSE_GREETING_AGGRESSIVE_PLOT_BUYING', 			'TXT_KEY_LEADER_CLPONTIAC_GREETING_AGGRESSIVE_PLOT_BUYING%', 			2),
('LEADER_CLPONTIAC', 	'RESPONSE_GREETING_HOSTILE_AGGRESSIVE_EXPANSION', 		'TXT_KEY_LEADER_CLPONTIAC_GREETING_HOSTILE_AGGRESSIVE_EXPANSION%', 		2),
('LEADER_CLPONTIAC', 	'RESPONSE_GREETING_AGGRESSIVE_EXPANSION', 				'TXT_KEY_LEADER_CLPONTIAC_GREETING_AGGRESSIVE_EXPANSION%', 				2),
('LEADER_CLPONTIAC', 	'RESPONSE_GREETING_FRIENDLY_STRONG_MILITARY', 			'TXT_KEY_LEADER_CLPONTIAC_GREETING_FRIENDLY_STRONG_MILITARY%', 			2),
('LEADER_CLPONTIAC', 	'RESPONSE_GREETING_FRIENDLY_STRONG_ECONOMY', 			'TXT_KEY_LEADER_CLPONTIAC_GREETING_FRIENDLY_STRONG_ECONOMY%', 			2),
('LEADER_CLPONTIAC', 	'RESPONSE_GREETING_HOSTILE_HUMAN_FEW_CITIES', 			'TXT_KEY_LEADER_CLPONTIAC_GREETING_HOSTILE_HUMAN_FEW_CITIES%', 			2),
('LEADER_CLPONTIAC', 	'RESPONSE_GREETING_HOSTILE_HUMAN_SMALL_ARMY', 			'TXT_KEY_LEADER_CLPONTIAC_GREETING_HOSTILE_HUMAN_SMALL_ARMY%', 			2),
('LEADER_CLPONTIAC', 	'RESPONSE_GREETING_HOSTILE_HUMAN_IS_WARMONGER', 		'TXT_KEY_LEADER_CLPONTIAC_GREETING_HOSTILE_HUMAN_IS_WARMONGER%', 		2),
('LEADER_CLPONTIAC', 	'RESPONSE_TOO_SOON_FOR_DOF', 							'TXT_KEY_LEADER_CLPONTIAC_TOO_SOON_FOR_DOF%', 							2),
('LEADER_CLPONTIAC', 	'RESPONSE_RESPONSE_TO_BEING_DENOUNCED', 				'TXT_KEY_LEADER_CLPONTIAC_RESPONSE_TO_BEING_DENOUNCED%', 				2),
('LEADER_CLPONTIAC', 	'RESPONSE_WORK_AGAINST_SOMEONE', 						'TXT_KEY_LEADER_CLPONTIAC_DENOUNCE%', 									2),
('LEADER_CLPONTIAC', 	'RESPONSE_AI_DOF_BACKSTAB', 							'TXT_KEY_LEADER_CLPONTIAC_DENOUNCE%', 									2),
('LEADER_CLPONTIAC', 	'RESPONSE_RESPONSE_TO_BEING_DENOUNCED', 				'TXT_KEY_LEADER_CLPONTIAC_RESPONSE_TO_BEING_DENOUNCED%', 				2),
('LEADER_CLPONTIAC', 	'RESPONSE_HUMAN_DOFED_FRIEND', 							'TXT_KEY_LEADER_CLPONTIAC_HUMAN_DOFED_FRIEND%', 						2),
('LEADER_CLPONTIAC', 	'RESPONSE_HUMAN_DOFED_ENEMY', 							'TXT_KEY_LEADER_CLPONTIAC_HUMAN_DOFED_ENEMY%', 							2),
('LEADER_CLPONTIAC', 	'RESPONSE_HUMAN_DENOUNCED_ENEMY', 						'TXT_KEY_LEADER_CLPONTIAC_HUMAN_DENOUNCED_ENEMY%', 						2),
('LEADER_CLPONTIAC', 	'RESPONSE_HUMAN_DENOUNCED_FRIEND', 						'TXT_KEY_LEADER_CLPONTIAC_HUMAN_DENOUNCED_FRIEND%', 					2),
('LEADER_CLPONTIAC', 	'RESPONSE_HUMAN_DOF_SO_AI_DOF', 						'TXT_KEY_LEADER_CLPONTIAC_HUMAN_DOF_SO_AI_DOF%', 						2),
('LEADER_CLPONTIAC', 	'RESPONSE_HUMAN_DENOUNCE_SO_AI_DENOUNCE', 				'TXT_KEY_LEADER_CLPONTIAC_HUMAN_DENOUNCE_SO_AI_DENOUNCE%', 				2),
('LEADER_CLPONTIAC', 	'RESPONSE_HUMAN_DOF_SO_AI_DENOUNCE', 					'TXT_KEY_LEADER_CLPONTIAC_HUMAN_DOF_SO_AI_DENOUNCE%', 					2),
('LEADER_CLPONTIAC', 	'RESPONSE_COOP_WAR_REQUEST', 							'TXT_KEY_LEADER_CLPONTIAC_COOP_WAR_REQUEST%', 							2),
('LEADER_CLPONTIAC', 	'RESPONSE_COOP_WAR_TIME', 								'TXT_KEY_LEADER_CLPONTIAC_COOP_WAR_TIME%', 								2),
('LEADER_CLPONTIAC', 	'RESPONSE_WORK_WITH_US', 								'TXT_KEY_LEADER_CLPONTIAC_DEC_FRIENDSHIP%', 							2),
('LEADER_CLPONTIAC', 	'RESPONSE_PLOT_BUYING_WARNING', 						'TXT_KEY_LEADER_CLPONTIAC_PLOT_BUYING_WARNING%', 						2),
('LEADER_CLPONTIAC', 	'RESPONSE_PLOT_BUYING_SERIOUS_WARNING', 				'TXT_KEY_LEADER_CLPONTIAC_PLOT_BUYING_SERIOUS_WARNING%', 				2),
('LEADER_CLPONTIAC', 	'RESPONSE_EXPANSION_SERIOUS_WARNING', 					'TXT_KEY_LEADER_CLPONTIAC_EXPANSION_SERIOUS_WARNING%', 					2),
('LEADER_CLPONTIAC', 	'RESPONSE_EXPANSION_WARNING', 							'TXT_KEY_LEADER_CLPONTIAC_EXPANSION_WARNING%', 							2),
('LEADER_CLPONTIAC', 	'RESPONSE_AGGRESSIVE_MILITARY_WARNING', 				'TXT_KEY_LEADER_CLPONTIAC_AGGRESSIVE_MILITARY_WARNING%', 				2),
('LEADER_CLPONTIAC', 	'RESPONSE_RETURNED_CIVILIAN', 							'TXT_KEY_LEADER_CLPONTIAC_RETURNED_CIVILIAN%', 							2),
('LEADER_CLPONTIAC', 	'RESPONSE_DECLARATION_PROTECT_CITY_STATE', 				'TXT_KEY_LEADER_CLPONTIAC_DECLARATION_PROTECT_CITY_STATE%', 			2),
('LEADER_CLPONTIAC', 	'RESPONSE_BULLIED_PROTECTED_CITY_STATE', 				'TXT_KEY_LEADER_CLPONTIAC_BULLIED_PROTECTED_CITY_STATE%', 				2),
('LEADER_CLPONTIAC', 	'RESPONSE_ATTACKED_PROTECTED_CITY_STATE', 				'TXT_KEY_LEADER_CLPONTIAC_ATTACKED_PROTECTED_CITY_STATEE%', 			2),
('LEADER_CLPONTIAC', 	'RESPONSE_DECLARATION_ABANDON_CITY_STATE', 				'TXT_KEY_LEADER_CLPONTIAC_DECLARATION_ABANDON_CITY_STATE%', 			2),
('LEADER_CLPONTIAC', 	'RESPONSE_DONT_SETTLE_YES', 							'TXT_KEY_LEADER_CLPONTIAC_DONT_SETTLE_YES%', 							2),
('LEADER_CLPONTIAC', 	'RESPONSE_DONT_SETTLE_NO', 								'TXT_KEY_LEADER_CLPONTIAC_DONT_SETTLE_NO%', 							2),
('LEADER_CLPONTIAC', 	'RESPONSE_LUXURY_TRADE', 								'TXT_KEY_LEADER_CLPONTIAC_LUXURY_TRADE%', 								2),
('LEADER_CLPONTIAC', 	'RESPONSE_OPEN_BORDERS_EXCHANGE', 						'TXT_KEY_LEADER_CLPONTIAC_OPEN_BORDERS_EXCHANGE%', 						2),
('LEADER_CLPONTIAC', 	'RESPONSE_REQUEST', 									'TXT_KEY_LEADER_CLPONTIAC_RESPONSE_REQUEST%', 							2),
('LEADER_CLPONTIAC', 	'RESPONSE_ATTACKED_HOSTILE', 							'TXT_KEY_LEADER_CLPONTIAC_ATTACKED_HOSTILE%', 							2),
('LEADER_CLPONTIAC', 	'RESPONSE_ATTACKED_WEAK_HOSTILE', 						'TXT_KEY_LEADER_CLPONTIAC_ATTACKED_HOSTILE%', 							2),
('LEADER_CLPONTIAC', 	'RESPONSE_ATTACKED_STRONG_HOSTILE', 					'TXT_KEY_LEADER_CLPONTIAC_ATTACKED_HOSTILE%', 							2),
('LEADER_CLPONTIAC', 	'RESPONSE_ATTACKED_EXCITED', 							'TXT_KEY_LEADER_CLPONTIAC_ATTACKED_EXCITED%', 							2),
('LEADER_CLPONTIAC', 	'RESPONSE_ATTACKED_WEAK_EXCITED', 						'TXT_KEY_LEADER_CLPONTIAC_ATTACKED_EXCITED%', 							2),
('LEADER_CLPONTIAC', 	'RESPONSE_ATTACKED_STRONG_EXCITED', 					'TXT_KEY_LEADER_CLPONTIAC_ATTACKED_EXCITED%', 							2),
('LEADER_CLPONTIAC', 	'RESPONSE_ATTACKED_SAD', 								'TXT_KEY_LEADER_CLPONTIAC_ATTACKED_SAD%', 								2),
('LEADER_CLPONTIAC', 	'RESPONSE_ATTACKED_BETRAYED', 							'TXT_KEY_LEADER_CLPONTIAC_ATTACKED_BETRAYED%', 							2),
('LEADER_CLPONTIAC', 	'RESPONSE_DOW_GENERIC', 								'TXT_KEY_LEADER_CLPONTIAC_DOW_GENERIC%', 								2),
('LEADER_CLPONTIAC', 	'RESPONSE_DOW_LAND', 									'TXT_KEY_LEADER_CLPONTIAC_DOW_LAND%', 									2),
('LEADER_CLPONTIAC', 	'RESPONSE_DOW_WORLD_CONQUEST', 							'TXT_KEY_LEADER_CLPONTIAC_DOW_WORLD_CONQUEST%', 						2),
('LEADER_CLPONTIAC', 	'RESPONSE_DOW_OPPORTUNITY', 							'TXT_KEY_LEADER_CLPONTIAC_DOW_OPPORTUNITY%', 							2),
('LEADER_CLPONTIAC', 	'RESPONSE_DOW_DESPERATE', 								'TXT_KEY_LEADER_CLPONTIAC_DOW_DESPERATE%', 								2),
('LEADER_CLPONTIAC', 	'RESPONSE_DOW_REGRET', 									'TXT_KEY_LEADER_CLPONTIAC_DOW_REGRET%', 								2),
('LEADER_CLPONTIAC', 	'RESPONSE_TOO_SOON_NO_PEACE', 							'TXT_KEY_LEADER_CLPONTIAC_TOO_SOON_NO_PEACE%', 							2),
('LEADER_CLPONTIAC', 	'RESPONSE_HOSTILE_AGGRESSIVE_MILITARY_WARNING_GOOD',	'TXT_KEY_LEADER_CLPONTIAC_GOOD%', 										2),
('LEADER_CLPONTIAC', 	'RESPONSE_AGGRESSIVE_MILITARY_WARNING_BAD',				'TXT_KEY_LEADER_CLPONTIAC_GOOD%', 										2),
('LEADER_CLPONTIAC', 	'RESPONSE_HOSTILE_WE_ATTACKED_MINOR_BAD',				'TXT_KEY_LEADER_CLPONTIAC_GOOD%', 										2),
('LEADER_CLPONTIAC', 	'RESPONSE_WE_ATTACKED_MINOR_BAD',						'TXT_KEY_LEADER_CLPONTIAC_GOOD%', 										2),
('LEADER_CLPONTIAC', 	'RESPONSE_HOSTILE_AGGRESSIVE_MILITARY_WARNING_BAD', 	'TXT_KEY_LEADER_CLPONTIAC_BAD%', 										2),
('LEADER_CLPONTIAC', 	'RESPONSE_HUMAN_ATTACKED_MINOR_BAD', 					'TXT_KEY_LEADER_CLPONTIAC_BAD%', 										2),
('LEADER_CLPONTIAC', 	'RESPONSE_HUMAN_SERIOUS_EXPANSION_WARNING_BAD', 		'TXT_KEY_LEADER_CLPONTIAC_BAD%', 										2),
('LEADER_CLPONTIAC', 	'RESPONSE_HUMAN_SERIOUS_PLOT_BUYING_WARNING_BAD', 		'TXT_KEY_LEADER_CLPONTIAC_BAD%', 										2),
('LEADER_CLPONTIAC', 	'RESPONSE_HUMAN_PLOT_BUYING_WARNING_BAD', 				'TXT_KEY_LEADER_CLPONTIAC_BAD%', 										2),
('LEADER_CLPONTIAC', 	'RESPONSE_AGGRESSIVE_MILITARY_WARNING_GOOD', 			'TXT_KEY_LEADER_CLPONTIAC_BAD%', 										2),
('LEADER_CLPONTIAC', 	'RESPONSE_HOSTILE_WE_ATTACKED_MINOR_GOOD', 				'TXT_KEY_LEADER_CLPONTIAC_BAD%', 										2),
('LEADER_CLPONTIAC', 	'RESPONSE_WE_ATTACKED_MINOR_GOOD', 						'TXT_KEY_LEADER_CLPONTIAC_BAD%', 										2),
('LEADER_CLPONTIAC', 	'RESPONSE_HUMAN_ATTACKED_MINOR_GOOD', 					'TXT_KEY_LEADER_CLPONTIAC_BAD%', 										2),
('LEADER_CLPONTIAC', 	'RESPONSE_HUMAN_SERIOUS_EXPANSION_WARNING_GOOD', 		'TXT_KEY_LEADER_CLPONTIAC_BAD%', 										2),
('LEADER_CLPONTIAC', 	'RESPONSE_HUMAN_SERIOUS_PLOT_BUYING_WARNING_GOOD', 		'TXT_KEY_LEADER_CLPONTIAC_BAD%', 										2),
('LEADER_CLPONTIAC', 	'RESPONSE_HUMAN_PLOT_BUYING_WARNING_GOOD', 				'TXT_KEY_LEADER_CLPONTIAC_BAD%', 										2);
--==========================================================================================================================
--==========================================================================================================================
INSERT INTO Language_en_US
(Tag,																	Text)
VALUES		('TXT_KEY_LEADER_CLPONTIAC_FIRSTGREETING_1',							'Welcome. Have you come to aid us, or shall we throw you into the sea?'),
			('TXT_KEY_LEADER_CLPONTIAC_FIRSTGREETING_2',							'Come. We are the Anishinaabe. We are loyal friends, and the fiercest of enemies.'),
			('TXT_KEY_LEADER_CLPONTIAC_DEFEATED_1',									'Time will bring your extermination.'),
			('TXT_KEY_LEADER_CLPONTIAC_REPEAT_TOO_MUCH_1',							'Stop blathering.'),
			('TXT_KEY_LEADER_CLPONTIAC_REPEAT_TRADE_TOO_MUCH_1',					'Your blathering doesn''t add any value.'),
			('TXT_KEY_LEADER_CLPONTIAC_GREETING_HOSTILE_HELLO_1',					'So. You dare to show us your face?'),
			('TXT_KEY_LEADER_CLPONTIAC_GREETING_POLITE_HELLO_1',					'Interesting. I hadn''t expected to see you today.'),
			('TXT_KEY_LEADER_CLPONTIAC_GREETING_HOSTILE_HUMAN_AT_WAR_1',			'Shreded clothing, ragged breaths, bruised and shaken. I trust that your war efforts are going about as well as I had expected.'),
			('TXT_KEY_LEADER_CLPONTIAC_GREETING_HUMAN_AT_WAR_1',					'Hmm. That war of yours is a shame. Can I help you?'),
			('TXT_KEY_LEADER_CLPONTIAC_AGGRESSIVE_MILITARY_WARNING_1',				'Is there a reason your armies are so close to Anishinaabe land? I''d hate to think that you wanted a fight, or something.'),
			('TXT_KEY_LEADER_CLPONTIAC_HOSTILE_AGGRESSIVE_MILITARY_WARNING_1',		'Pssh. Do you bring an army to the Anishinaabe? It will profit you nothing but death.'),
			('TXT_KEY_LEADER_CLPONTIAC_GREETING_AGGRESSIVE_PLOT_BUYING_1',			'You see this land as "your land" and "my land" but that is not the way of the Anishinaabe. Do not attempt to make all of this "your land," or things will go badly for you.'),
			('TXT_KEY_LEADER_CLPONTIAC_GREETING_HOSTILE_AGGRESSIVE_PLOT_BUYING_1',	'You would be wise to stop calling all the lands your own, before we Anishinaabe remove you from them.'),
			('TXT_KEY_LEADER_CLPONTIAC_PLOT_BUYING_WARNING_1',						'You see this land as "your land" and "my land" but that is not the way of the Anishinaabe. Do not attempt to make all of this "your land," or things will go badly for you.'),
			('TXT_KEY_LEADER_CLPONTIAC_PLOT_BUYING_SERIOUS_WARNING_1',				'You would be wise to stop calling all the lands your own, before we Anishinaabe remove you from them.'),
			('TXT_KEY_LEADER_CLPONTIAC_GREETING_AGGRESSIVE_EXPANSION_1',			'If we are to avoid war, you should not settle any closer to my lands. My people are given to defending our ways and our lands from foreign influences.'),
			('TXT_KEY_LEADER_CLPONTIAC_GREETING_HOSTILE_AGGRESSIVE_EXPANSION_1',	'The cities that you are erecting across these lands are pissing me off. If my vision is blocked by any more of your squalid hovels that clutter the horizon, I will have to do a bit of cleaning.'),
			('TXT_KEY_LEADER_CLPONTIAC_EXPANSION_WARNING_1',						'I warned you about your cities being too close to our lands. Did you listen? No. Will we come to blows? Possibly.'),
			('TXT_KEY_LEADER_CLPONTIAC_EXPANSION_SERIOUS_WARNING_1',				'More cities blocking out the sun on the hills and plains around us. I wonder how beautiful they will look when they are set to the flame.'),
			('TXT_KEY_LEADER_CLPONTIAC_GREETING_FRIENDLY_STRONG_MILITARY_1',		'When two mighty nations meet each other, and they become friends, it is a bright day indeed.'),
			('TXT_KEY_LEADER_CLPONTIAC_GREETING_FRIENDLY_STRONG_ECONOMY_1',			'I am impressed by your great wealth, since I know that it has not come at the expense of my people. I salute you.'),
			('TXT_KEY_LEADER_CLPONTIAC_GREETING_HOSTILE_HUMAN_FEW_CITIES_1',		'So few cities. They look lonely and waifish, like orphan children. Like crippled dogs just waiting for a hungry bear.'),
			('TXT_KEY_LEADER_CLPONTIAC_GREETING_HOSTILE_HUMAN_SMALL_ARMY_1',		'I think I just saw your only warrior. He looked lonely and scared. Perhaps it would be good if my warriors or maybe my arrows would keep him compnay.'),
			('TXT_KEY_LEADER_CLPONTIAC_GREETING_HOSTILE_HUMAN_IS_WARMONGER_1',		'The thing about being a monster who lusts only after the flesh of children and the screams of dying soldiers is that you become blind to the spear that is set before you. I am such a spear.'),
			('TXT_KEY_LEADER_CLPONTIAC_TOO_SOON_FOR_DOF_1',							'Do you not realize that the Anishinaabe have long memories and wise elders? We will not give you peace as long as we live.'),
			('TXT_KEY_LEADER_CLPONTIAC_DENOUNCE_1',									'I have told the others of your evil ways and how you wish to teach them to others.'),
			('TXT_KEY_LEADER_CLPONTIAC_DENOUNCE_2',									'Just in case the leaders of other nations are blind or addled and cannot see with their own eyes, I have told them of what you have done.'),
			('TXT_KEY_LEADER_CLPONTIAC_RESPONSE_TO_BEING_DENOUNCED_1',				'Oh, really. You truly believe that the others will believe your word on this matter?'),
			('TXT_KEY_LEADER_CLPONTIAC_HUMAN_DOFED_FRIEND_1',						'{1_CivName} is a good leader, who respects our old ways. I applaud your decision to become friends with them.'),
			('TXT_KEY_LEADER_CLPONTIAC_HUMAN_DOFED_ENEMY_1',						'You besoil yourself, befriending that fatherless dog, that desolate swine, {1_CivName}!'),
			('TXT_KEY_LEADER_CLPONTIAC_HUMAN_DENOUNCED_FRIEND_1',					'Beware. {1_CivName} is a friend to the Anishinaabe, and we defend our friends.'),
			('TXT_KEY_LEADER_CLPONTIAC_HUMAN_DENOUNCED_ENEMY_1',					'Together, we will be able to deal with {1_CivName}, swiftly and adequately.'),
			('TXT_KEY_LEADER_CLPONTIAC_HUMAN_DOF_SO_AI_DOF_1',						'I trust your judge of character. I will also seek friendship with {1_CivName}.'),
			('TXT_KEY_LEADER_CLPONTIAC_HUMAN_DOF_SO_AI_DENOUNCE_1',					'If a man walks with a dog, eats with a dog, and sleeps with a dog, that man is a dog. You are a dog. {1_CivName} is clearly no better than one, either.'),
			('TXT_KEY_LEADER_CLPONTIAC_HUMAN_DENOUNCE_SO_AI_DENOUNCE_1',			'You are a shrewd leader. If you feel that {1_CivName} is despicable, than I too shall denounce this evil.'),
			('TXT_KEY_LEADER_CLPONTIAC_COOP_WAR_REQUEST_1',							'My spies are at the {1_Playername:textkey}''s gates. When I give the signal, they will open them. Do you wish to join us in the ensuing slaughter?'),
			('TXT_KEY_LEADER_CLPONTIAC_COOP_WAR_TIME_1',							'The time is now. Come, let us ride straight into the heart of {1_PlayerName:textkey}''s most defendable cites!'),
			('TXT_KEY_LEADER_CLPONTIAC_DEC_FRIENDSHIP_1',							'It is hard to find people who live by their traditions. I believe that you are one. Will you join the Anishinaabe and safeguard our ways from foreign influences?'),
			('TXT_KEY_LEADER_CLPONTIAC_RETURNED_CIVILIAN_1',						'Truly, you are a leader of a character not often seen in these days.'),
			('TXT_KEY_LEADER_CLPONTIAC_MINOR_CIV_COMPETITION_1',					'{1_MinorCivName:textkey} is a member of my circle of friends. Do not attempt to break our pact of trust. It is never truly broken.'),
			('TXT_KEY_LEADER_CLPONTIAC_MINOR_CIV_COMPETITION_2',					'I am amused by your overtures towards {1_MinorCivName:textkey}. In a time of trouble, I will send the Midew, our medicine men, to remind them of where their allegience truly lies. We will see what happens then.'),
			('TXT_KEY_LEADER_CLPONTIAC_DECLARATION_PROTECT_CITY_STATE_1',			'{2_MajorCivName:textkey} announces to the world that it is now protecting {1_MinorCivName:textkey}. Attacking the City-State will greatly damage relations and may lead to war, especially if they send a Midew to them.'),
			('TXT_KEY_LEADER_CLPONTIAC_DECLARATION_ABANDON_CITY_STATE_1',			'{2_MajorCivName:textkey} has taken back its guarantee of protecting {1_MinorCivName:textkey}.'),
			('TXT_KEY_LEADER_CLPONTIAC_ATTACKED_PROTECTED_CITY_STATE_1',			'You think that you are a wolf, to harry {@1_MinorCivName}? You are but a dog. I am a man. With a spear. Do not try my patience.'),
			('TXT_KEY_LEADER_CLPONTIAC_BULLIED_PROTECTED_CITY_STATE_1',				'You mock the Anishinaabe, acting as if we cannot protect {@1_MinorCivName}, that our word is weak and of no consequence. If you reach your hand out again to do wickedness, there will be dire consequences.'),
			('TXT_KEY_LEADER_CLPONTIAC_DONT_SETTLE_NO_1',							'You do not dictate the ways of the Anishinaabe.'),
			('TXT_KEY_LEADER_CLPONTIAC_DONT_SETTLE_YES_1',							'Alright. I will not settle here. But I will remember this day.'),
			('TXT_KEY_LEADER_CLPONTIAC_LUXURY_TRADE_1',								'It seems that not everything about your ways are despicable to the Anishinaabe. That is very interesting.'),
			('TXT_KEY_LEADER_CLPONTIAC_OPEN_BORDERS_EXCHANGE_1',					'To keep in contact with our fellow Midew, we must travel through your lands. Give us passage.'),
			('TXT_KEY_LEADER_CLPONTIAC_RESPONSE_REQUEST_1',							'I seek a favor from you.'),
			('TXT_KEY_LEADER_CLPONTIAC_ATTACKED_HOSTILE_1',							'I have been waiting for a chance to stick you like the swine you are.'),
			('TXT_KEY_LEADER_CLPONTIAC_ATTACKED_EXCITED_1',							'I will light all of your cities ablaze, and send your people with their tails beneath their legs, back where they came from.'),
			('TXT_KEY_LEADER_CLPONTIAC_ATTACKED_SAD_1',								'If you were honorable, if you respected the old ways, we would not be here today, sworn enemies.'),
			('TXT_KEY_LEADER_CLPONTIAC_ATTACKED_BETRAYED_1',						'Only a weak dog bites his friend, and then runs back to his house to hide from the coming wrath. And there will be wrath. Much wrath.'),
			('TXT_KEY_LEADER_CLPONTIAC_DOW_GENERIC_1',								'My men are already within your walls. Your defenses will not save you.'),
			('TXT_KEY_LEADER_CLPONTIAC_DOW_GENERIC_2',								'Your time has come. Finally.'),
			('TXT_KEY_LEADER_CLPONTIAC_DOW_LAND_1',									'You took this land and called it your own. It is time to break the hand that you use to grasp what you cannot have.'),
			('TXT_KEY_LEADER_CLPONTIAC_DOW_WORLD_CONQUEST_1',						'I will throw your corpse to the ground once I pierce it with my spear and rend it with my hands.'),
			('TXT_KEY_LEADER_CLPONTIAC_DOW_OPPORTUNITY_1',							'Even the most noble wolf will eat a lame deer. And you are a lame deer if I have ever seen one.'),
			('TXT_KEY_LEADER_CLPONTIAC_DOW_DESPERATE_1',							'If our ways are to survive, you must die.'),
			('TXT_KEY_LEADER_CLPONTIAC_DOW_BETRAYAL_1',								'Now is the time that we have been waiting for you. My spies have compromised your defenses. The Midew have gone to rally our allies. You are finished, dog.'),
			('TXT_KEY_LEADER_CLPONTIAC_TOO_SOON_NO_PEACE_1',						'Do you mock me with this offer?'),
			('TXT_KEY_LEADER_CLPONTIAC_BAD_1',										'No. Try harder.'),
			('TXT_KEY_LEADER_CLPONTIAC_GOOD_1',										'Why not?');