--==========================================================================================================================
-- CBRX TSLs
--==========================================================================================================================
----------------------------------------------------------------------------------------------------------------------------
-- Civilization_CBRX_TSLs
----------------------------------------------------------------------------------------------------------------------------
INSERT INTO Civilization_CBRX_TSLs 
		(CivilizationType,								X,		Y,		IsIsland)
VALUES	('CIVILIZATION_BABYLON',						9,		0,		0), --0 (default) = false, 1 = true
		('CIVILIZATION_AGLA_ESTONIA',					32,		76,		0),
		('CIVILIZATION_AGLA_ZELENY_KLYN',				95,		75,		0),
		('CIVILIZATION_AGLA_SCYTHIA',					37,		67,		0),
		('CIVILIZATION_AGLA_HANSE_WULLENWEVER',			19,		69,		0),
		('CIVILIZATION_SAS_AURES',						17,		46,		0),
		('CIVILIZATION_SENSHI_BANGLADESH',				72,		49,		0),
		('CIVILIZATION_RHO_BJARMIA',					35,		86,		0),
		('CIVILIZATION_SENSHI_BUNUBA',					94,		21,		0),
		('CIVILIZATION_SAS_BERZEG',						40,		61,		0),
		('CIVILIZATION_DMS_ETHIOPIA_YAQOB',				37,		33,		0),
		('CIVILIZATION_URDNOT_REV_FRANCE',				12,		62,		0),
		('CIVILIZATION_GT_ROURAN',						76,		73,		0),
		('CIVILIZATION_GT_TERNATE',						97,		34,		1),
		('CIVILIZATION_THP_HERERO',						28,		12,		0),
		('CIVILIZATION_TCM_HYKSOS',						35,		46,		0),
		('CIVILIZATION_RHO_ITELMEN',					104,	85,		0),
		('CIVILIZATION_SENSHI_HIDEYOSHI',				100,	66,		1),
		('CIVILIZATION_JFD_KALMAR_UNION',				22,		73,		0),
		('CIVILIZATION_LUNG_KIPCHAKS',					56,		72,		0),
		('CIVILIZATION_PB_LANFANG',						86,		30,		1),
		('CIVILIZATION_THP_LUBA',						32,		22,		0),
		('CIVILIZATION_DMS_MINAEANS',					42,		38,		0),
		('CIVILIZATION_JWW_MARAVI',						37,		17,		0),
		('CIVILIZATION_MC_RAPA_NUI',					143,	24,		1),
		('CIVILIZATION_MC_MYSORE',						64,		36,		0),
		('CIVILIZATION_SENSHI_NEW_SOUTH_WALES',			109,	11,		0),
		('CIVILIZATION_SENSHI_PAKISTAN',				57,		44,		0),
		('CIVILIZATION_JFD_PAPAL_STATES_JULIUS_II',		21,		53,		0),
		('CIVILIZATION_ER_PEGU',						75,		43,		0),
		('CIVILIZATION_MC_PHOENICIA',					38,		50,		0),
		('CIVILIZATION_TCM_AVIS_PORTUGAL',				5,		50,		0),
		('CIVILIZATION_JWW_QARA_KHITAI',				62,		67,		0),
		('CIVILIZATION_SAS_RYUKYU',						94,		56,		1),
		('CIVILIZATION_ASQ_SCOTLAND_MARY',				7,		75,		1),
		('CIVILIZATION_JWW_SEYCHELLES',					50,		25,		1),
		('CIVILIZATION_AKKADIAN_MOD',					47,		48,		0),
		('CIVILIZATION_THP_TANG',						80,		64,		0),
		('CIVILIZATION_ASQ_UMHAILL',					0,		70,		1),
		('CIVILIZATION_NC_CEBU',						94,		40,		1),
		('CIVILIZATION_RHO_VYATKA',						46,		76,		0),
		('CIVILIZATION_JFD_WALLACHIA',					30,		60,		0),
		('CIVILIZATION_SENSHI_YUNNAN',					80,		52,		0),
		('CIVILIZATION_THP_KET',						61,		83,		0),
		('CIVILIZATION_TCM_BACTRIA',					57,		59,		0),
		('CIVILIZATION_NC_ZAZZAU',						23,		32,		0),
		('CIVILIZATION_NC_WASSOULOU',					10,		31,		0),
		('CIVILIZATION_CL_TLINGIT',						120,	81,		0),
		('CIVILIZATION_CLANISHINAABE',					143,	78,		0),
		('CIVILIZATION_JWW_KARANKAWA',					136,	59,		0),
		('CIVILIZATION_LEU_ONONDAGA_TADODAHO',			152,	73,		0),
		('CIVILIZATION_NC_PONCA',						136,	71,		0),
		('CIVILIZATION_ORG_COIOT_POMO',					125,	66,		0),
		('CIVILIZATION_TG_SUSQUEHANNOCK',				152,	68,		0),
		('CIVILIZATION_NORTE_CHICO_MOD',				147,	30,		0),
		('CIVILIZATION_MC_YANOMAMI',					153,	39,		0),
		('CIVILIZATION_ZRQ_TEO_SPEAROWL',				135,	50,		0),
		('CIVILIZATION_ASQ_XARAGUA',					154,	50,		1),
		('CIVILIZATION_RHO_CHONO',						148,	10,		1),
		('CIVILIZATION_THP_GUAYCURU',					156,	24,		0),
		('CIVILIZATION_SAS_XAVANTE',					159,	31,		0),
		('CIVILIZATION_RHO_POTIGUARA',					168,	33,		0); --If making additions, make sure the LAST ) ends with a ;
--==========================================================================================================================
--==========================================================================================================================