INSERT INTO Religions 
			(Type,						Description,						Civilopedia,							IconAtlas,						PortraitIndex,	IconString)						   
VALUES		
			('RELIGION_KUKSU',			'TXT_KEY_RELIGION_KUKSU',			'TXT_KEY_RELIGION_KUKSU_PEDIA',			'CALIFORNIA_RELIGIONS_ATLAS',	0,				'[ICON_RELIGION_KUKSU]'),
			('RELIGION_DATURA',			'TXT_KEY_RELIGION_DATURA',			'TXT_KEY_RELIGION_DATURA_PEDIA',		'CALIFORNIA_RELIGIONS_ATLAS',	1,				'[ICON_RELIGION_DATURA]'),
			('RELIGION_DREAMING',		'TXT_KEY_RELIGION_DREAMING',		'TXT_KEY_RELIGION_DREAMING_PEDIA',		'CALIFORNIA_RELIGIONS_ATLAS',	2,				'[ICON_RELIGION_DREAMING]'),
			('RELIGION_WAASHAT',		'TXT_KEY_RELIGION_WAASHAT',			'TXT_KEY_RELIGION_WAASHAT_PEDIA',		'CALIFORNIA_RELIGIONS_ATLAS',	3,				'[ICON_RELIGION_WAASHAT]'),
			('RELIGION_WORLD_RENEWAL',	'TXT_KEY_RELIGION_WORLD_RENEWAL',	'TXT_KEY_RELIGION_WORLD_RENEWAL_PEDIA',	'CALIFORNIA_RELIGIONS_ATLAS',	4,				'[ICON_RELIGION_WORLD_RENEWAL]'),
			('RELIGION_BOLE_MARU',		'TXT_KEY_RELIGION_BOLE_MARU',		'TXT_KEY_RELIGION_BOLE_MARU_PEDIA',		'CALIFORNIA_RELIGIONS_ATLAS',	5,				'[ICON_RELIGION_BOLE_MARU]');